# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 08:43
from __future__ import unicode_literals

import another.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('another', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='file',
            field=models.FileField(upload_to=another.models.user_directory_path),
        ),
    ]
