# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
            ],
        ),
    ]
