# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_client_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuring_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('avg_ex_hour', models.FloatField()),
                ('stomach', models.CharField(max_length=200)),
                ('avg_sleep_hour', models.FloatField()),
                ('mood', models.CharField(max_length=200)),
            ],
        ),
    ]
