# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20161225_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuring_data',
            name='image',
            field=models.ImageField(default='', upload_to=project.models.user_directory_path),
        ),
    ]
