# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_measuring_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuring_data',
            name='image',
            field=models.ImageField(default='', upload_to='.'),
        ),
    ]
