# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20161226_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuring_data',
            name='image',
            field=models.FileField(default='', upload_to='.'),
        ),
    ]
