# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20161227_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=project.models.user_directory_iamgepath)),
            ],
        ),
    ]
